### ISSUE TITLE
Any plan to support Apple Silicon M1 chip?

### ISSUE THREAD

**Issue by MobilEKG** [UIWidgets/com.unity.uiwidgets#18]
It looks currently version only supports macOS(Intel64, Metal/OpenGLCore). Is there any plan to support Apple M1 series?
(This is a question, not an issue)

**Comment by zhuxingwei** [comment]
Yes M1-chip support is indeed one of the most desired features for UIWidgets 2.0 users so far. The team has made it a critical issue in our roadmap and made serious investigation on it already. 

According to the result of our investigation, we have concluded that, only if we upgraded the native flutter engine from 1.17 to the latest 3.XX, the M1-chip support can be done. Good news is that we are already working on the upgrade in late 2022 and aim to finish it in 2023. Thanks for your patient and we will let you know when it is done.
