### ISSUE TITLE
xcode 报 libUIWidgets.a 找不到 EAGLContext 

### ISSUE THREAD

**Issue by jet6666** [UIWidgets/com.unity.uiwidgets#3]
>  | ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/zooling/Desktop/uiwdget/s2/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
>   -- | --
   | Undefined symbols for architecture arm64:
  | "_OBJC_CLASS_$_EAGLContext", referenced from:
  | objc-class-ref in libUIWidgets.a(libUIWidgets.o)
  | "_glDeleteTextures", referenced from:
  | l2690 in libUIWidgets.a(libUIWidgets.o)
  | l2695 in libUIWidgets.a(libUIWidgets.o)
  | "_glDeleteFramebuffers", referenced from:
  | l2690 in libUIWidgets.a(libUIWidgets.o)
  | "_glBindFramebuffer", referenced from:
  | l2688 in libUIWidgets.a(libUIWidgets.o)
  | "_glBindTexture", referenced from:
  | l2688 in libUIWidgets.a(libUIWidgets.o)
  | "_glCheckFramebufferStatus", referenced from:
  | l2688 in libUIWidgets.a(libUIWidgets.o)
  | "_glGetIntegerv", referenced from:
  | l2688 in libUIWidgets.a(libUIWidgets.o)
  | "_glGenFramebuffers", referenced from:
  | l2688 in libUIWidgets.a(libUIWidgets.o)
  | "_glFramebufferTexture2D", referenced from:
  | l2688 in libUIWidgets.a(libUIWidgets.o)
  | ld: symbol(s) not found for architecture arm64
  | clang: error: linker command failed with exit code 1 (use -v to see invocation)
 

![报错截图](https://github.com/jet6666/jet6666.github.io/blob/master/%E6%88%AA%E5%B1%8F2022-09-27%20%E4%B8%8A%E5%8D%8810.49.35.png?raw=true)

项目已经加上 OpenGLES.framework

![报错截图](https://github.com/jet6666/jet6666.github.io/blob/master/%E6%88%AA%E5%B1%8F2022-09-27%20%E4%B8%8A%E5%8D%8810.51.47.png?raw=true)

unity.package manifest.json 配置以及原libuiwidgets.a 文件如下
![截图](https://github.com/jet6666/jet6666.github.io/blob/master/%E6%88%AA%E5%B1%8F2022-09-27%20%E4%B8%8A%E5%8D%8811.19.39.png?raw=true)

**Comment by jet6666** [comment]
Jesus, It's Unity's BUG
In  2020.3.24f1c2  there is no "OpenGLES" options in Building for iOS (But Android have this option )

solved by  Unity 2019.4.29f1c2

**Comment by zhuxingwei** [comment]
No you can still use Unity 2020 LTS. Please refer to Question 3 in our [FAQ](https://github.com/UIWidgets/com.unity.uiwidgets#faq) for the details.

**Comment by jet6666** [comment]
> No you can still use Unity 2020 LTS. Please refer to Question 3 in our [FAQ](https://github.com/UIWidgets/com.unity.uiwidgets#faq) for the details.

thanks ,  :thumbsup:
