### ISSUE TITLE
数字宽度不一致，用了FontFeature.tabularFigures()也无效

### ISSUE THREAD

**Issue by xuexirong** [UIWidgets/com.unity.uiwidgets#6]
![image](https://user-images.githubusercontent.com/13816024/192471330-2184b869-e1ed-445e-8ca6-fba8ab31c89c.png)
这个是uiwidgets
![image](https://user-images.githubusercontent.com/13816024/192471436-47756687-1fd6-4d52-aae4-e1451818aed2.png)
这个是flutter

**Comment by zhuxingwei** [comment]
Thanks for the report!

We will investigate this issue later when we have time and let you know if we have any progress

**Comment by zhuxingwei** [comment]
The issue is fixed in #10 and please note that the **tabularFigures** feature looks different for different fonts as stated at https://api.flutter.dev/flutter/dart-ui/FontFeature/FontFeature.tabularFigures.html
